const Bag = [
  {
    id: 1,
    title: '캠플 백팩 12L Light Beige',
    price: '119,000',
    img: '/img/bag/bag01.jpg',
    isNew: true,
  },
  {
    id: 2,
    title: '캠플 백팩 12L Black',
    price: '119,000',
    img: '/img/bag/bag02.jpg',
    isNew: true,
  },
  {
    id: 3,
    title: '캠플 백팩 15L Fog Gray',
    price: '129,000',
    img: '/img/bag/bag03.jpg',
    isNew: true,
  },
  {
    id: 4,
    title: '캠플 백팩 15L Black',
    price: '129,000',
    img: '/img/bag/bag04.jpg',
    isNew: true,
  },
  {
    id: 5,
    title: '포프에셈 미니백 4L Cream Beige',
    price: '69,000',
    img: '/img/bag/bag05.jpg',
    isNew: true,
  },
  {
    id: 6,
    title: '포프에셈 미니백 4L Black',
    price: '69,000',
    img: '/img/bag/bag06.jpg',
    isNew: true,
  },
  {
    id: 7,
    title: '포프에셈 미니백 6L Khaki Gray',
    price: '79,000',
    img: '/img/bag/bag07.jpg',
    isNew: true,
  },
  {
    id: 8,
    title: '포프에셈 미니백 6L Rustic Khaki',
    price: '79,000',
    img: '/img/bag/bag08.jpg',
    isNew: true,
  },
  {
    id: 9,
    title: '스테디 백팩 25L Rustic Khaki',
    price: '169,000',
    img: '/img/bag/bag09.jpg',
    isNew: true,
  },
  {
    id: 10,
    title: '스테디 슬링백 5L Fog Gray',
    price: '89,000',
    img: '/img/bag/bag10.jpg',
    isNew: true,
  },
  {
    id: 11,
    title: '스테디 캔버스 토트백 13L Chocolate Khaki',
    price: '129,000',
    img: '/img/bag/bag11.jpg',
    isNew: true,
  },
  {
    id: 12,
    title: '스테디 힙색 2L Vintage Gray',
    price: '79,000',
    img: '/img/bag/bag12.jpg',
    isNew: true,
  },
];

export default Bag;