const ReviewData = [
  {
    id: 1,
    rating: 5,
    option: "95(M)",
    content: "좋아요 아주 좋아요",
    images: ["/img/review/review01.webp"],
    user: "otstar",
    height: 173,
    weight: 68,
    topSize: "M",
    bottomSize: "30in",
    helpful: 6,
    comments: 1,
    date: "2026. 4. 5.",
    tags: ["전체", "디자인", "착용감", "색상", "소재"],
  },
  {
    id: 2,
    rating: 5,
    option: "95(M)",
    content: "처음 구매했는데 가성비 소재 및 컬러 디자인 모두 만족합니다.",
    images: ["/img/review/review02.webp"],
    user: "박정민",
    height: 173,
    weight: 68,
    topSize: "M",
    bottomSize: "30in",
    helpful: 3,
    comments: 0,
    date: "2026. 4. 3.",
    tags: ["전체", "디자인", "라인(핏)", "가격"],
  },
  {
    id: 3,
    rating: 4,
    option: "100(L)",
    content: "실물 색감이 괜찮고 편하게 입기 좋았어요.",
    images: ["/img/review/review03.webp"],
    user: "김도윤",
    height: 176,
    weight: 72,
    topSize: "L",
    bottomSize: "32in",
    helpful: 2,
    comments: 0,
    date: "2026. 4. 1.",
    tags: ["전체", "색상", "착용감"],
  },
  {
    id: 4,
    rating: 5,
    option: "105(XL)",
    content: "포장 상태 좋고 원단도 부드러워서 만족합니다.",
    images: ["/img/review/review04.webp"],
    user: "이수현",
    height: 168,
    weight: 58,
    topSize: "M",
    bottomSize: "28in",
    helpful: 1,
    comments: 0,
    date: "2026. 3. 29.",
    tags: ["전체", "소재", "배송"],
  },
  {
    id: 5,
    rating: 5,
    option: "110(2XL)",
    content: "후드 핏이 자연스럽고 컬러가 생각보다 더 예쁩니다.",
    images: ["/img/review/review05.webp"],
    user: "최민호",
    height: 184,
    weight: 85,
    topSize: "2XL",
    bottomSize: "34in",
    helpful: 4,
    comments: 0,
    date: "2026. 3. 27.",
    tags: ["전체", "디자인", "색상", "라인(핏)"],
  },
];

export default ReviewData;